Address DR-20
utkdigitalinitiatives/utk_isl_xml_forms pull request #32
Opened 2017-04-11 21:00 UTC by CanOfBees

**JIRA Ticket**: [DR-20](https://jira.lib.utk.edu/projects/DR/issues/DR-20)

# What does this Pull Request do?
Adds a sample MODS DSID and a roth_post_process.xsl for removing empty elements and empty attributes.

# What's new?
A transform that removes empty elements and empty attributes.

# How should this be tested?

Please use Option 1
1. Option 1:
	* Import the Form
	* Associate it with a content model
	* Apply any additional / related transforms
	* Create a new record and select the newly associated form
	* Edit that record to see if the form still behaves correctly
2. Option 2:
	* vagrant destroy
	* vagrant up

# Interested parties
@markpbaggett

2017-04-12 12:36 UTC, markpbaggett commented
@CanOfBees, review is underway.

2017-04-12 12:38 UTC, markpbaggett commented
Also, we should really change the p.r. template here for testing. You can't test this with "vagrant destroy" / "vagrant up."  

Since I just posted that comment to this p.r., do you mind just adding this to this pull request.  That way, no need to open another.

2017-04-12 12:40 UTC, CanOfBees commented
@markpbaggett agreed. i'll add the change.

2017-04-12 12:43 UTC, markpbaggett commented
Okay, how about something like this:

`## How should this be 

Describe what steps to take to test this change.

**Examples:**
* Import the Form, Associate it with a content model, Apply any additional / related transforms, Create a new record and select the newly associated form, Edit that record to see if the form still behaves correctly
* vagrant destroy and vagrant up
* Associate transform to existing xml form
`

Not necessarily like that, but you know what I mean.

2017-04-12 14:31 UTC, CanOfBees commented
@markpbaggett take a look at the new verbiage. Thanks!

2017-04-12 17:45 UTC, markpbaggett requested changes
line 30 of PULL_REQUEST_TEMPLATE is wrong.  

Should be:  * `sudo cp $REPO_NAME/dir-path/transform.xsl /var/www/drupal/sites/all/modules/islandora_xml_forms/builder/self_transforms/`

Everything else looks good though. Works!

2017-04-12 17:55 UTC, markpbaggett requested changes
One little change.  All else looks good though.

2017-04-12 17:55 UTC, markpbaggett commented on .github/PULL_REQUEST_TEMPLATE.md
> +    * `sudo cp $REPO_NAME/dir-path/transform.xsl /var/www/drupal/sites/all/modules/islandora_xml_transforms/builder/self_transforms/`
This should be: 

* `sudo cp $REPO_NAME/dir-path/transform.xsl /var/www/drupal/sites/all/modules/islandora_xml_forms/builder/self_transforms/`

2017-04-13 00:34 UTC, CanOfBees commented
@markpbaggett thanks for catching that.

2017-04-13 00:35 UTC, markpbaggett approved these changes

2017-04-13 00:35 UTC, merged

2017-04-13 11:34 UTC, markpbaggett commented
@CanOfBees, I've merged.  Feel free to mark DR-20 as "Done."  I created a DR-21.  Either of us can do that.